FROM tensorflow/tensorflow:1.15.4-gpu-py3

# nvidia-docker 1.0
LABEL com.nvidia.volumes.needed="nvidia_driver"
LABEL com.nvidia.cuda.version="${CUDA_VERSION}"

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    NVIDIA_REQUIRE_CUDA="cuda>=8.0" \
    LANG=C.UTF-8

RUN mkdir /gpt-2
WORKDIR /gpt-2
COPY download_model.py .
COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN python3 download_model.py 774M
ADD . /gpt-2

# RUN apt update
# RUN apt install -y python3-dev python3-pip git
# RUN pip3 install --upgrade pip setuptools requests

# RUN pip install nvidia-pyindex
# RUN pip install nvidia-tensorflow[horovod]
# RUN pip list | grep nvidia